name: Deploy Farg and Fargpalett

on:
  push:
    branches: [main]

jobs:
  build_fargpalett:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir out
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.1'
    - run: go get
      working-directory: fargpalett
    - run: CGO_ENABLED=1 go build -o fargpalett main.go
      working-directory: fargpalett
    - uses: actions/upload-artifact@v2
      with:
        name: server
        path: fargpalett/fargpalett

  build_farg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir out
    - uses: actions/setup-node@v1
    - run: npm install
      working-directory: farg
    - run: npm run build
      working-directory: farg
    - uses: actions/upload-artifact@v2
      with:
        name: client
        path: farg/dist/

  copy_to_server:
    runs-on: ubuntu-latest
    needs: [build_fargpalett, build_farg]
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: server
    - uses: actions/download-artifact@v2
      with:
        name: client
        path: static
    - name: Copying to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        rm: false
        source: "./"
        target: "${{ secrets.REMOTE_DIR }}"
    - name: Re-Start server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: chmod +x ${{ secrets.REMOTE_DIR }}/fargpalett && tmux send-keys -t farg_prod 'C-c' && tmux send-keys -t farg_prod 'cd ${{ secrets.REMOTE_DIR }}' ENTER && tmux send-keys -t farg_prod './fargpalett -port=:${{ secrets.PROD_PORT }}' ENTER
